### ISSUE TITLE
data should be a function?

### ISSUE THREAD

**Issue by bado22** [TinyAnvil/tiny-money-webpack#1]
https://github.com/TinyAnvil/tiny-money-webpack/blob/0709bf5836abb2a1a1cac58950655dafb5947abb/js/root/root.js#L9

Hey @tyvdh I've never used Vue before so I'm just getting situated with it, but I noticed that data here is a pojo rather than a function. Based on [this part of the docs](https://vuejs.org/v2/guide/components.html#data-Must-Be-a-Function) it feels like it should be a function. Thoughts?

**Comment by kalepail** [comment]
Nope. It would be if this were a Component, but it's just a basic Vue instance.
https://vuejs.org/v2/guide/instance.html#Data-and-Methods

You'll notice a few actual components around and in that case yes, the data key should be a function.

Nice try though! 😛

**Comment by bado22** [comment]
heh - must try harder next time! That makes sense, thanks for explaining.
